server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.120:33306/yun6?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: E:\my_java\uploads\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1 # 当前机器id
    datacenterId: 1 # 序列号
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 5000
    httpReadTimeoutMs: 10000
    notifyUrl: http://www.leyou.com