server:
  port: 8084
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.42.120
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAI4FkBpYg435XnJd9MRF6v # 你自己的accessKeyId
    accessKeySecret: CntYYhCURpQ9ZCbyitdjED0SrDgfVB # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_177355065 # 模板名称