server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
hystrix:
  command:
    default: #可以指定类或具体方法
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6500
ribbon:
  ConnectTimeout: 1000 #ribbon连接超时时长
  ReadTimeout: 2000 #ribbon读取超时时长
  maxAutoRetries: 0 #当前服务器重试次数
  maxAutoRetriesNextServer: 1 #切换服务重试次数
zuul:
  prefix: /api  #添加路由规则
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    upload-service:
      serviceId: upload-service
      path: /upload/**
      strip-prefix: false
  add-host-header: true
  sensitive-headers:
ly:
  jwt:
    pubKeyPath: E:\my_java\uploads\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item